# site properties and page defaults
title: Camacho-Aguilar Lab
subtitle: at Centro Andaluz de Biología del Desarrollo (CABD)
description: The Sy(Stem)s Developmental Biology Lab.
header: images/mainimage.jpg
footer: images/mainimage.jpg

# site social media and other links
links:
  email: ecamagu@upo.es
  orcid: 0000-0001-9058-6663
  google-scholar: dMKRYTAAAAAJ
  github: ecamacho90
  twitter: elecamagu
  youtube: elecamagu

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
