- id: doi:10.1101/2024.03.13.584912
  title: Endogenous Nodal switches Wnt interpretation from posteriorization to germ
    layer differentiation in geometrically constrained human pluripotent cells
  authors:
  - Miguel Angel Ortiz-Salazar
  - Elena Camacho-Aguilar
  - Aryeh Warmflash
  publisher: Pre-print on bioRxiv
  date: '2024-03-14'
  link: https://doi.org/gtm6h7
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: images/MAOS_Micropattern.png
  
- id: doi:10.1101/2022.11.11.516212
  title: Combinatorial interpretation of BMP and WNT allows BMP to act as a morphogen
    in time but not in concentration
  authors:
  - Elena Camacho-Aguilar<sup>+</sup>
  - Sumin Yoon
  - Miguel A. Ortiz-Salazar
  - Aryeh Warmflash<sup>+</sup>
  publisher: Pre-print on bioRxiv
  date: '2022-11-12'
  link: https://doi.org/gtkxk5
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: images/Graphical_Abstract_v5_Final.jpg
  
- id: doi:10.1038/s41467-022-34363-w
  title: Membrane potential drives the exit from pluripotency and cell fate commitment
    via calcium and mTOR
  authors:
  - Emily Sempou
  - Valentyna Kostiuk
  - Jie Zhu
  - M. Cecilia Guerra
  - Leonid Tyan
  - Woong Hwang
  - Elena Camacho-Aguilar
  - Michael J. Caplan
  - David Zenisek
  - Aryeh Warmflash
  - Nick D. L. Owens
  - Mustafa K. Khokha
  publisher: Nature Communications
  date: '2022-11-05'
  link: https://doi.org/grpqvq
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: images/Membrane_potential.jpg
  
- id: doi:10.1016/j.cels.2021.08.013
  title: Statistically derived geometrical landscapes capture principles of decision-making
    dynamics during cell fate transitions
  authors:
  - Meritxell Saez<sup>*</sup>
  - Robert Blassberg<sup>*</sup>
  - Elena Camacho-Aguilar<sup>*</sup>
  - Eric D. Siggia
  - David A. Rand<sup>+</sup>
  - James Briscoe<sup>+</sup>
  publisher: Cell Systems
  date: '2022-01-01'
  link: https://doi.org/gmv9z3
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: https://www.cell.com/cms/attachment/716ef181-b032-4bec-818f-c35a02401580/fx1.jpg
  
- id: doi:10.1371/journal.pcbi.1009034
  title: Quantifying cell transitions in C. elegans with data-fitted landscape models
  authors:
  - Elena Camacho-Aguilar<sup>+</sup>
  - Aryeh Warmflash
  - David A. Rand<sup>+</sup>
  publisher: PLOS Computational Biology
  date: '2021-06-01'
  link: https://doi.org/gtkxk6
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: images/VulvalDevelopment_Striking_Image.jpg
  
- id: doi:10.1101/2021.03.11.434982
  title: A quantitative landscape of cell fate transitions identifies principles of
    cellular decision-making
  authors:
  - Meritxell Saez<sup>*</sup>
  - R. Blassberg<sup>*</sup>
  - E. Camacho-Aguilar<sup>*</sup>
  - E. D. Siggia
  - D. Rand<sup>+</sup>
  - J. Briscoe<sup>+</sup>
  publisher: Pre-print on bioRxiv
  date: '2021-03-11'
  link: https://doi.org/gsx3cv
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: https://www.biorxiv.org/sites/default/files/biorxiv_logo_homepage.png
  
- id: doi:10.1101/2021.01.22.426019
  title: Quantifying cell transitions in <i>C. elegans</i> with data-fitted landscape
    models
  authors:
  - Elena Camacho-Aguilar<sup>+</sup>
  - Aryeh Warmflash
  - David A. Rand<sup>+</sup>
  publisher: Pre-print on bioRxiv
  date: '2021-01-22'
  link: https://doi.org/gszbh8
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: https://www.biorxiv.org/sites/default/files/biorxiv_logo_homepage.png
  
- id: doi:10.1016/bs.ctdb.2019.11.010
  title: Insights into mammalian morphogen dynamics from embryonic stem cell systems
  authors:
  - Elena Camacho-Aguilar
  - Aryeh Warmflash
  publisher: Current Topics in Developmental Biology
  date: '2020-01-01'
  link: https://doi.org/gtkxk7
  orcid: 0000-0001-9058-6663
  plugin: sources.py
  file: sources.yaml
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0070215320X00032-cov200h.gif
